[project]
name = "loan-custom-rag"
version = "0.0.1"
description = "loan-custom-rag"
authors = [{ name = "John Doe", email = "john.doe@myemail.com" }]
dependencies = [
    "langchain-classic>=1.0.0",
    "uipath-langchain>=0.1.0",
]
requires-python = ">=3.11"
